project:
  type: website
  output-dir: docs

website:
  title: "Sara Colando"
  favicon: personal-website-hex-sticker.png
  navbar:
    logo: personal-website-hex-sticker.png
    right:
      - href: about.qmd
        text: "About"
      - href: research.qmd
        text: "Research"
      - href: projects.qmd
        text: "TidyTuesdays"
      - href: blog.qmd
        text: "Blogs"
      - href: cv.qmd
        text: "CV"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

